# Generated by Django 4.1.1 on 2022-11-23 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('case', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.case')),
                ('cooler', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.cooler')),
                ('cpu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.cpu')),
                ('graphics', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.graphics')),
                ('motherboard', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.motherboard')),
                ('powersupply', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.powersupply')),
                ('ram', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.ram')),
                ('storage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='components.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
